name: news_app
description: "Flutter News App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.19.0
  floor: ^1.5.0
  get_it: ^7.7.0
  retrofit: ^4.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  floor_generator: ^1.5.0
  retrofit_generator: ^8.1.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/vectors/
